# Generated by Django 5.1.1 on 2024-11-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about_banner_facts_delete_fermer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facts',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='products',
            name='bio',
        ),
    ]
