# Generated by Django 5.1.1 on 2024-11-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='features/')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
