# Generated by Django 5.1.1 on 2024-11-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bio',
            new_name='span',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='bio',
            new_name='span',
        ),
    ]
