# Generated by Django 5.1.1 on 2024-11-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_bio_blog_span_rename_bio_team_span'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='span',
            field=models.IntegerField(),
        ),
    ]
